{"success": false, "error": "Traceback (most recent call last):\n  File \"/home/im/.pyenv/versions/3.9.1/lib/python3.9/site-packages/falcon_analyzer-0.2.28-py3.9.egg/falcon/__main__.py\", line 835, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/home/im/.pyenv/versions/3.9.1/lib/python3.9/site-packages/falcon_analyzer-0.2.28-py3.9.egg/falcon/__main__.py\", line 87, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/home/im/.pyenv/versions/3.9.1/lib/python3.9/site-packages/crytic_compile/crytic_compile.py\", line 667, in compile_all\n    compilations.append(CryticCompile(filename, **kwargs))\n  File \"/home/im/.pyenv/versions/3.9.1/lib/python3.9/site-packages/crytic_compile/crytic_compile.py\", line 131, in __init__\n    self._compile(**kwargs)\n  File \"/home/im/.pyenv/versions/3.9.1/lib/python3.9/site-packages/crytic_compile/crytic_compile.py\", line 553, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/home/im/.pyenv/versions/3.9.1/lib/python3.9/site-packages/crytic_compile/platform/solc.py\", line 149, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"/home/im/.pyenv/versions/3.9.1/lib/python3.9/site-packages/crytic_compile/platform/solc.py\", line 278, in _get_targets_json\n    return _run_solc(\n  File \"/home/im/.pyenv/versions/3.9.1/lib/python3.9/site-packages/crytic_compile/platform/solc.py\", line 483, in _run_solc\n    raise InvalidCompilation(\ncrytic_compile.platform.exceptions.InvalidCompilation: . is a directory. Expected a Solidity file when not using a compilation framework.\n", "results": {}, "engine_version": "0.2.28"}